services:
  database:
    image: postgres:13-alpine
    container_name: database
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - "${DATABASE_HOST_DIRECTORY}:/var/lib/postgresql/data"
      - ./host/database:/host
    working_dir: /host
    networks:
      - owl-network

  webapp:
    image: alexgs99/node:2
    container_name: webapp
    restart: unless-stopped
    ports:
      - "${WEBAPP_PORT}:3000"
      - "5555:5555"
    volumes:
      - .:/bare-owls
    working_dir: /bare-owls/webapp
    networks:
      - owl-network
    environment:
      - DATABASE_URL
    command: npm run dev

networks:
  owl-network:
    driver: bridge
    name: owl-network
