-- FUNCTION: public.post_authorized_claim("Post")

-- 2021-09-20: The DB seems to be a weird state. Everything works, but I get
-- some permissions error when I try to update this stored procedure in Hasura
-- (and the content of it doesn't even show up in pgAdmin). I can probably fix
-- this by deleting the DB on disk and recreating. I have all of the data in my
-- seed files, so it's not a problem. I should find a different migration tool,
-- however, since trying to put this function in the Prisma migration file is
-- what caused the problems.

-- Code generated by pgAdmin 4 v5.6
-- See [Hasura docs][1] for another example
-- [1]: https://hasura.io/docs/latest/graphql/core/databases/postgres/schema/computed-fields.html#scalar-computed-fields
CREATE OR REPLACE FUNCTION public.post_authorized_claim(post_row "Post")
    RETURNS text
    LANGUAGE 'sql'
    STABLE
AS $BODY$
    SELECT post_row."channelId" || ':' || "ChannelTier".slug FROM "Post" JOIN "ChannelTier" ON post_row."tierId" = "ChannelTier".id
$BODY$;
